#!/usr/bin/env python3
"""Render a static, offline HTML dashboard from signal-capture evidence.

Reads docs/evidence/signal-captures/*.json (written by capture_signals.py)
and emits a single self-contained HTML file — no server, no build step, no
framework, no network fetch. Open it directly in a browser. This is the
"validation" axis of the observability dashboard split (the other two —
Decision Journey, and live Jaeger — are separate, higher-cost pieces; this one
is free because it only reads files already on disk).

Usage:
    python -m tools.render_dashboard [--in DIR] [--out FILE]
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).parent.parent


def load_captures(in_dir: Path) -> list[dict]:
    captures = []
    for fpath in sorted(in_dir.glob("*.json")):
        if fpath.name == "summary.json":
            continue
        captures.append(json.loads(fpath.read_text()))
    return captures


def render(captures: list[dict]) -> str:
    n_detected = sum(1 for c in captures if c["detected"])
    n_fp = sum(1 for c in captures if c["false_positive_ticks"])
    n_total = len(captures)
    gate_pass = n_detected == n_total and n_fp == 0
    gate_status = "good" if gate_pass else ("critical" if n_detected == 0 else "warning")
    gate_label = "READY" if gate_pass else "NOT READY"

    payload = json.dumps(captures)

    cards = "\n".join(_scenario_card(i, c) for i, c in enumerate(captures))

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>PatchTST Signal Validation — Go/No-Go</title>
<style>
{_CSS}
</style>
</head>
<body>
<div class="viz-root">
  <header class="page-header">
    <div>
      <h1>PatchTST Signal Validation</h1>
      <p class="muted">Offline capture — {n_total} scenario(s), no cluster, no cloud spend</p>
    </div>
    <button id="theme-toggle" class="theme-toggle" aria-label="Toggle dark mode">◐</button>
  </header>

  <section class="gate-tile status-{gate_status}">
    <div class="gate-icon">{"✓" if gate_pass else "✕"}</div>
    <div>
      <div class="gate-hero">{n_detected} / {n_total}</div>
      <div class="gate-label">{gate_label} — deploy gate {"cleared" if gate_pass else "NOT cleared"}</div>
    </div>
  </section>

  <section class="cards">
{cards}
  </section>

  <footer class="muted">Generated by tools/render_dashboard.py from docs/evidence/signal-captures/</footer>
</div>

<script type="application/json" id="capture-data">{payload}</script>
<script>
{_JS}
</script>
</body>
</html>
"""


def _scenario_card(idx: int, c: dict) -> str:
    status = "good" if (c["detected"] and not c["false_positive_ticks"]) else (
        "warning" if c["detected"] else "critical"
    )
    badge = "DETECTED" if c["detected"] else "MISSED"
    icon = "✓" if c["detected"] else "✕"
    latency = c["detection_latency_ticks"] if c["detection_latency_ticks"] is not None else "—"
    fp = len(c["false_positive_ticks"])
    return f"""    <article class="card">
      <div class="card-head">
        <h2>{c["scenario"]}</h2>
        <p class="muted">{c["description"]}</p>
      </div>
      <div class="badge-row">
        <span class="badge status-{status}"><span aria-hidden="true">{icon}</span> {badge}</span>
        <div class="stat"><span class="stat-label">Latency</span><span class="stat-value">{latency}<span class="stat-unit"> ticks</span></span></div>
        <div class="stat"><span class="stat-label">False positives</span><span class="stat-value">{fp}</span></div>
        <div class="stat"><span class="stat-label">Runtime</span><span class="stat-value">{c["elapsed_s"]}<span class="stat-unit"> s</span></span></div>
      </div>
      <div class="chart-wrap" data-scenario-index="{idx}">
        <svg class="chart-svg" data-scenario-index="{idx}" role="img" aria-label="Score over ticks for {c["scenario"]}"></svg>
        <div class="tooltip" hidden></div>
      </div>
      <button class="table-toggle" data-scenario-index="{idx}" aria-expanded="false">Show table view</button>
      <div class="table-wrap" data-scenario-index="{idx}" hidden></div>
    </article>"""


_CSS = """
.viz-root {
  color-scheme: light;
  --surface-1:      #fcfcfb;
  --page-plane:     #f9f9f7;
  --text-primary:   #0b0b0b;
  --text-secondary: #52514e;
  --text-muted:     #898781;
  --gridline:       #e1e0d9;
  --baseline:       #c3c2b7;
  --border:         rgba(11,11,11,0.10);
  --series-1:       #2a78d6;
  --status-good:     #0ca30c;
  --status-warning:  #fab219;
  --status-critical: #d03b3b;
}
@media (prefers-color-scheme: dark) {
  :root:where(:not([data-theme="light"])) .viz-root {
    color-scheme: dark;
    --surface-1:      #1a1a19;
    --page-plane:     #0d0d0d;
    --text-primary:   #ffffff;
    --text-secondary: #c3c2b7;
    --text-muted:     #898781;
    --gridline:       #2c2c2a;
    --baseline:       #383835;
    --border:         rgba(255,255,255,0.10);
    --series-1:       #3987e5;
    --status-good:     #0ca30c;
    --status-warning:  #fab219;
    --status-critical: #e66767;
  }
}
:root[data-theme="dark"] .viz-root {
  color-scheme: dark;
  --surface-1:      #1a1a19;
  --page-plane:     #0d0d0d;
  --text-primary:   #ffffff;
  --text-secondary: #c3c2b7;
  --text-muted:     #898781;
  --gridline:       #2c2c2a;
  --baseline:       #383835;
  --border:         rgba(255,255,255,0.10);
  --series-1:       #3987e5;
  --status-good:     #0ca30c;
  --status-warning:  #fab219;
  --status-critical: #e66767;
}

* { box-sizing: border-box; }
body {
  margin: 0;
  background: var(--page-plane);
  font-family: system-ui, -apple-system, "Segoe UI", sans-serif;
  color: var(--text-primary);
}
.viz-root { max-width: 960px; margin: 0 auto; padding: 32px 20px 60px; }
.muted { color: var(--text-secondary); font-size: 13px; margin: 4px 0 0; }

.page-header { display: flex; align-items: flex-start; justify-content: space-between; margin-bottom: 20px; }
.page-header h1 { font-size: 20px; margin: 0; }
.theme-toggle {
  border: 1px solid var(--border); background: var(--surface-1); color: var(--text-primary);
  border-radius: 6px; width: 32px; height: 32px; cursor: pointer; font-size: 14px;
}

.gate-tile {
  display: flex; align-items: center; gap: 16px;
  background: var(--surface-1); border: 1px solid var(--border); border-radius: 10px;
  padding: 20px 24px; margin-bottom: 24px;
}
.gate-icon { font-size: 28px; line-height: 1; }
.status-good .gate-icon, .status-good .badge { color: var(--status-good); }
.status-warning .gate-icon, .status-warning .badge { color: var(--status-warning); }
.status-critical .gate-icon, .status-critical .badge { color: var(--status-critical); }
.gate-hero { font-size: 32px; font-weight: 600; line-height: 1.1; }
.gate-label { color: var(--text-secondary); font-size: 13px; margin-top: 2px; }

.cards { display: flex; flex-direction: column; gap: 16px; }
.card { background: var(--surface-1); border: 1px solid var(--border); border-radius: 10px; padding: 20px; }
.card-head h2 { font-size: 15px; margin: 0; font-family: ui-monospace, monospace; }

.badge-row { display: flex; align-items: center; gap: 24px; margin: 14px 0 10px; flex-wrap: wrap; }
.badge {
  display: inline-flex; align-items: center; gap: 6px; font-weight: 600; font-size: 12px;
  border: 1px solid currentColor; border-radius: 999px; padding: 4px 10px;
}
.stat { display: flex; flex-direction: column; }
.stat-label { color: var(--text-muted); font-size: 11px; }
.stat-value { font-size: 16px; font-weight: 600; }
.stat-unit { font-size: 11px; font-weight: 400; color: var(--text-secondary); }

.chart-wrap { position: relative; }
.chart-svg { width: 100%; height: 220px; display: block; }
.axis-label, .ref-label { fill: var(--text-muted); font-size: 10px; font-family: system-ui, sans-serif; }
.gridline { stroke: var(--gridline); stroke-width: 1; }
.baseline { stroke: var(--baseline); stroke-width: 1; }
.ref-line { stroke: var(--text-muted); stroke-width: 1; stroke-dasharray: 3 3; }
.score-line { fill: none; stroke: var(--series-1); stroke-width: 2; stroke-linejoin: round; stroke-linecap: round; }
.score-dot { stroke: var(--surface-1); stroke-width: 2; }
.crosshair { stroke: var(--text-muted); stroke-width: 1; pointer-events: none; }

.tooltip {
  position: absolute; pointer-events: none; background: var(--surface-1); color: var(--text-primary);
  border: 1px solid var(--border); border-radius: 6px; padding: 8px 10px; font-size: 12px;
  box-shadow: 0 4px 12px rgba(0,0,0,0.12); white-space: nowrap; transform: translate(-50%, -110%);
}
.tooltip .tt-value { font-weight: 600; }
.tooltip .tt-row { display: flex; gap: 8px; justify-content: space-between; }

.table-toggle {
  margin-top: 10px; background: none; border: 1px solid var(--border); color: var(--text-secondary);
  border-radius: 6px; padding: 6px 10px; font-size: 12px; cursor: pointer;
}
.table-wrap table { width: 100%; border-collapse: collapse; margin-top: 10px; font-size: 12px; }
.table-wrap th, .table-wrap td { text-align: left; padding: 6px 8px; border-bottom: 1px solid var(--gridline); font-variant-numeric: tabular-nums; }
.table-wrap th { color: var(--text-muted); font-weight: 500; }
footer.muted { margin-top: 24px; text-align: center; }
"""

_JS = r"""
(function () {
  const root = document.documentElement;
  const toggle = document.getElementById("theme-toggle");
  const saved = localStorage.getItem("dv-theme");
  if (saved) root.setAttribute("data-theme", saved);
  toggle.addEventListener("click", function () {
    const next = root.getAttribute("data-theme") === "dark" ? "light" : "dark";
    root.setAttribute("data-theme", next);
    localStorage.setItem("dv-theme", next);
  });

  const captures = JSON.parse(document.getElementById("capture-data").textContent);
  const SEVERITY_VAR = {
    normal: "--status-good",
    warning: "--status-warning",
    critical: "--status-critical",
  };

  const vizRoot = document.querySelector(".viz-root");
  function cssVar(name) {
    return getComputedStyle(vizRoot).getPropertyValue(name).trim();
  }

  function renderChart(svg, capture) {
    const timeline = capture.timeline;
    const w = 640, h = 220, padL = 36, padR = 12, padT = 12, padB = 24;
    const plotW = w - padL - padR, plotH = h - padT - padB;

    const ticks = timeline.map(function (e) { return e.tick; });
    const scores = timeline.map(function (e) { return e.score; });
    const maxScore = Math.max.apply(null, scores.concat([3.0])) * 1.15;
    const minTick = Math.min.apply(null, ticks), maxTick = Math.max.apply(null, ticks);

    function x(tick) { return padL + (maxTick === minTick ? 0 : (tick - minTick) / (maxTick - minTick) * plotW); }
    function y(score) { return padT + plotH - (score / maxScore) * plotH; }

    svg.setAttribute("viewBox", "0 0 " + w + " " + h);
    svg.innerHTML = "";

    function el(tag, attrs) {
      const e = document.createElementNS("http://www.w3.org/2000/svg", tag);
      for (const k in attrs) e.setAttribute(k, attrs[k]);
      return e;
    }

    // gridlines (y: 0, 1.8 warning, 3.0 critical) — skip a label that would
    // collide with the previous one (min 10px vertical gap) rather than
    // overlapping text; the gridline itself is still drawn.
    let lastLabelY = -Infinity;
    [0, 1.8, 3.0].forEach(function (val) {
      if (val > maxScore) return;
      const gy = y(val);
      svg.appendChild(el("line", { x1: padL, x2: w - padR, y1: gy, y2: gy, class: val === 0 ? "baseline" : "ref-line" }));
      if (Math.abs(gy - lastLabelY) >= 10) {
        const label = el("text", { x: 4, y: gy + 3, class: "axis-label" });
        label.textContent = val.toFixed(1);
        svg.appendChild(label);
        lastLabelY = gy;
      }
    });

    // incident_at reference (ground truth)
    const ix = x(capture.incident_at);
    svg.appendChild(el("line", { x1: ix, x2: ix, y1: padT, y2: h - padB, class: "ref-line" }));
    const ilabel = el("text", { x: ix + 4, y: padT + 10, class: "ref-label" });
    ilabel.textContent = "incident onset";
    svg.appendChild(ilabel);

    // detected marker
    if (capture.first_incident_tick != null) {
      const dx = x(capture.first_incident_tick);
      const dlabel = el("text", { x: dx + 4, y: padT + 22, class: "ref-label" });
      dlabel.textContent = "→ INCIDENT";
      svg.appendChild(dlabel);
    }

    // score line
    const pathD = timeline.map(function (e, i) {
      return (i === 0 ? "M" : "L") + x(e.tick).toFixed(1) + "," + y(e.score).toFixed(1);
    }).join(" ");
    svg.appendChild(el("path", { d: pathD, class: "score-line" }));

    // severity-colored dots
    timeline.forEach(function (e) {
      const color = cssVar(SEVERITY_VAR[e.severity] || "--status-good");
      svg.appendChild(el("circle", {
        cx: x(e.tick), cy: y(e.score), r: 4.5, fill: color, class: "score-dot",
        "data-tick": e.tick,
      }));
    });

    // x-axis ticks (first, mid, last)
    [ticks[0], ticks[Math.floor(ticks.length / 2)], ticks[ticks.length - 1]].forEach(function (t) {
      const label = el("text", { x: x(t), y: h - 6, class: "axis-label", "text-anchor": "middle" });
      label.textContent = t;
      svg.appendChild(label);
    });

    return { x: x, y: y, padT: padT, plotH: plotH };
  }

  function attachCrosshair(wrap, svg, capture, scales) {
    const tooltip = wrap.querySelector(".tooltip");
    const timeline = capture.timeline;

    function nearest(clientTick) {
      let best = timeline[0], bestDist = Infinity;
      timeline.forEach(function (e) {
        const d = Math.abs(e.tick - clientTick);
        if (d < bestDist) { bestDist = d; best = e; }
      });
      return best;
    }

    svg.addEventListener("pointermove", function (evt) {
      const rect = svg.getBoundingClientRect();
      const px = (evt.clientX - rect.left) / rect.width * 640;
      const minTick = timeline[0].tick, maxTick = timeline[timeline.length - 1].tick;
      const padL = 36, padR = 12, plotW = 640 - padL - padR;
      const clientTick = minTick + (px - padL) / plotW * (maxTick - minTick);
      const entry = nearest(clientTick);
      const sx = scales.x(entry.tick), sy = scales.y(entry.score);

      tooltip.hidden = false;
      tooltip.style.left = (sx / 640 * rect.width) + "px";
      tooltip.style.top = (sy / 220 * rect.height) + "px";
      tooltip.innerHTML =
        '<div class="tt-row"><span>tick</span><span class="tt-value">' + entry.tick + '</span></div>' +
        '<div class="tt-row"><span>score</span><span class="tt-value">' + entry.score + '</span></div>' +
        '<div class="tt-row"><span>severity</span><span class="tt-value">' + entry.severity + '</span></div>' +
        '<div class="tt-row"><span>regime</span><span class="tt-value">' + (entry.regime || "—") + '</span></div>';
    });
    svg.addEventListener("pointerleave", function () { tooltip.hidden = true; });
  }

  document.querySelectorAll(".chart-svg").forEach(function (svg) {
    const idx = svg.getAttribute("data-scenario-index");
    const capture = captures[idx];
    const scales = renderChart(svg, capture);
    const wrap = svg.closest(".chart-wrap");
    attachCrosshair(wrap, svg, capture, scales);
  });

  document.querySelectorAll(".table-toggle").forEach(function (btn) {
    btn.addEventListener("click", function () {
      const idx = btn.getAttribute("data-scenario-index");
      const capture = captures[idx];
      const target = document.querySelector('.table-wrap[data-scenario-index="' + idx + '"]');
      const expanded = btn.getAttribute("aria-expanded") === "true";
      if (!expanded && !target.dataset.built) {
        const rows = capture.timeline.map(function (e) {
          return "<tr><td>" + e.tick + "</td><td>" + e.severity + "</td><td>" + e.score +
            "</td><td>" + (e.regime || "—") + "</td><td>" + (e.mode || "—") + "</td><td>" + e.method + "</td></tr>";
        }).join("");
        target.innerHTML =
          "<table><thead><tr><th>Tick</th><th>Severity</th><th>Score</th><th>Regime</th><th>Mode</th><th>Method</th></tr></thead>" +
          "<tbody>" + rows + "</tbody></table>";
        target.dataset.built = "1";
      }
      target.hidden = expanded;
      btn.setAttribute("aria-expanded", String(!expanded));
      btn.textContent = expanded ? "Show table view" : "Hide table view";
    });
  });
})();
"""


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--in", dest="in_dir", default=str(ROOT / "docs/evidence/signal-captures"))
    parser.add_argument("--out", default=str(ROOT / "docs/evidence/signal-captures/dashboard.html"))
    args = parser.parse_args(argv)

    in_dir = Path(args.in_dir)
    captures = load_captures(in_dir)
    if not captures:
        print(f"no capture JSON files found in {in_dir}")
        return 1

    html = render(captures)
    out_path = Path(args.out)
    out_path.write_text(html)
    print(f"wrote {out_path} ({len(captures)} scenario(s))")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
